name: Gource Action Build
on:
  release:
    types:
      - published

jobs:
  gource-action:
    name: 'Local visualisation'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Gource Action'
        uses: nbprojekt/gource-action@master
        with:
          git_url: ./
          avatars_url: ./avatars/
          gource_title: 'Gource action'
          logo_url: 'https://user-images.githubusercontent.com/24683383/92398226-79a40680-f128-11ea-9f54-6ccbaca4a6a5.png'

      - name: 'Upload gource video'
        uses: actions/upload-artifact@v4
        with:
          name: Gource action
          path: ./gource/gource.mp4

  gource-docker-cli:
    name: 'Docker CLI visualisation'
    runs-on: ubuntu-latest

    steps:
      - name: 'Gource Action'
        uses: nbprojekt/gource-action@master
        with:
          git_url: https://github.com/docker/cli
          gource_title: 'Docker CLI'
          logo_url: 'https://user-images.githubusercontent.com/24683383/92395924-70189f80-f124-11ea-815c-aa4d9f4de29d.png'
          gource_resolution: '1080p'
          gource_fps: 60
          gource_font_size: 40
          gource_start_date: '2016-04-18'
          gource_stop_date: '2019-12-31'

      - name: 'Upload gource video'
        uses: actions/upload-artifact@v4
        with:
          name: Docker CLI
          path: ./gource/gource.mp4
