name: Sync labels
on:
  push:
    branches:
      - master
    paths:
      - .github/labels.yml
jobs:
  sync-labels:
    name: 'Sync labels'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Label Syncer
        uses: micnncim/action-label-syncer@v0.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        with:
          manifest: .github/labels.yml
